"""Mock-only taxonomy helpers for reason-code registry and compatibility checks."""

from __future__ import annotations

from typing import Any

from lima_office.runtime.errors import PolicyDenyError


TAXONOMY_VERSION = "taxonomy-reason-v1"
SUPPORTED_TAXONOMY_VERSIONS = frozenset(
    {
        "taxonomy-reason-v1",
        "taxonomy-reason-v2",
        "taxonomy-reason-v3",
        "taxonomy-recon-v1",
    }
)

REASON_CODE_CATEGORIES = frozenset(
    {
        "reconciliation",
        "linkage",
        "evidence",
        "export_delete",
        "governance",
        "guardian",
        "replay",
        "approval_binding",
        "transaction",
        "health",
        "blocked_mvp",
        "tenant_isolation",
    }
)

REASON_CODE_STATUSES = frozenset({"active", "deprecated", "blocked", "reserved"})
REASON_CODE_SEVERITIES = frozenset({"info", "warning", "degraded", "blocked", "critical"})

UNKNOWN_REASON_CODE_POLICIES = frozenset({"fail_closed", "display_unknown", "blocked_mvp"})
DEPRECATED_REASON_CODE_POLICIES = frozenset({"allow_with_warning", "fail_closed", "blocked_mvp"})

REASON_CODE_REGISTRY: dict[str, dict[str, Any]] = {
    "recon_missing_guardian_decision": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "recon_stale_guardian_decision": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "recon_mismatched_approval_binding": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "recon_mismatched_token_verification": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "recon_replay_record_missing": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "recon_replay_record_mismatch": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "recon_evidence_ref_missing": {
        "category": "reconciliation",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "recon_coordinator_event_mismatch": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "recon_cross_tenant_linkage": {
        "category": "tenant_isolation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "blocked_mvp_authorization_attempt": {
        "category": "blocked_mvp",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "export_delete_conflict_active": {
        "category": "export_delete",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "export_delete_preservation_hold_active": {
        "category": "export_delete",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "export_delete_retention_window_active": {
        "category": "export_delete",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "export_delete_review_required": {
        "category": "export_delete",
        "status": "deprecated",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": False,
        "fail_closed_required": False,
        "replaced_by": "export_delete_conflict_active",
        "aliases": ["export_delete_review_required_legacy"],
    },
    "export_delete_blocked_mvp": {
        "category": "export_delete",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "evidence_ref_missing": {
        "category": "evidence",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "evidence_failed_closed_required": {
        "category": "evidence",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "export_manifest_redaction_required": {
        "category": "evidence",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "blocked_mvp_export_delete_execution": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "health_guardian_replay_denied": {
        "category": "health",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": False,
        "fail_closed_required": False,
        "aliases": [],
    },
    "worker_stale": {
        "category": "health",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": False,
        "fail_closed_required": False,
        "aliases": [],
    },
    "worker_quarantined": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "worker_revoked": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "evidence_writer_degraded": {
        "category": "health",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": False,
        "aliases": [],
    },
    "guardian_denied": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "approval_expired": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "approval_revoked": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "token_mismatch": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_revoked": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_consent_missing": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_scope_overbroad": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_scope_denied": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_revocation_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_object_auth_missing": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_property_auth_missing": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_outbound_action_blocked": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_live_blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_prompt_injection_risk": {
        "category": "guardian",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_rate_limit_missing": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_secret_policy_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_export_delete_impact_unknown": {
        "category": "export_delete",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_provider_high_risk": {
        "category": "governance",
        "status": "active",
        "severity": "degraded",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": False,
        "aliases": [],
    },
    "connector_provider_critical_risk": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_disable_switch_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_disable_switch_failed": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_revocation_unverified": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_revocation_drill_failed": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_token_rotation_missing": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_outbound_capability_blocked": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_prompt_injection_blocked": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_cross_tenant_blocked": {
        "category": "tenant_isolation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_reconciliation_drift": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "consent_revoked_but_ready": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "scope_overbroad_but_invocation_requested": {
        "category": "linkage",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "provider_critical_but_ready": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "revocation_drill_failed_but_enabled": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "disable_switch_missing_but_ready": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "outbound_missing_approval": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "tainted_connector_payload_blocked": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_cross_tenant_linkage": {
        "category": "tenant_isolation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_evidence_missing": {
        "category": "evidence",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_trust_revoked_but_allowed": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_score_below_threshold": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_score_failed_closed": {
        "category": "reconciliation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_score_degraded": {
        "category": "governance",
        "status": "active",
        "severity": "degraded",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": False,
        "aliases": [],
    },
    "connector_slo_missed": {
        "category": "reconciliation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_slo_stale": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_reconciliation_stale": {
        "category": "reconciliation",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_revocation_propagation_pending": {
        "category": "linkage",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_revocation_propagation_missed": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_disable_verification_missed": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_source_of_truth_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_source_of_truth_conflict": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_owner_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_owner_stale": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_owner_conflict": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_sod_violation": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_escalation_overdue": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_revocation_owner_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_disable_owner_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_accountability_failed_closed": {
        "category": "reconciliation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_acceptance_blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_defaults_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_defaults_stale": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_defaults_override_review_required": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_slo_target_missing": {
        "category": "reconciliation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_slo_target_missed": {
        "category": "reconciliation",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_score_threshold_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_score_threshold_stale": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_threshold_blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_default_outbound_blocked": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "connector_provider_category_blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_failed": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_expired": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "trust_root_unknown": {
        "category": "health",
        "status": "active",
        "severity": "degraded",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "trust_root_failed": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "reference_value_missing": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "reference_value_stale": {
        "category": "health",
        "status": "active",
        "severity": "degraded",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "reference_value_revoked": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "endorsement_missing": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "endorsement_revoked": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "endorsement_expired": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "appraisal_policy_missing": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "appraisal_policy_revoked": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "appraisal_failed": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "appraisal_inconclusive": {
        "category": "health",
        "status": "active",
        "severity": "degraded",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_result_expired": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_quarantine_required": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_reference_mismatch": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_lineage_stale": {
        "category": "health",
        "status": "active",
        "severity": "degraded",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_lineage_revoked": {
        "category": "health",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_lineage_conflicted": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "revocation_propagation_pending": {
        "category": "transaction",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "revocation_propagation_failed": {
        "category": "transaction",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "verifier_authority_missing": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "verifier_authority_revoked": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "reference_authority_missing": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "endorsement_authority_missing": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "quarantine_clearance_sod_required": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_result_trust_conflict": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_reconciliation_drift": {
        "category": "reconciliation",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_revocation_pending": {
        "category": "transaction",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_revocation_not_propagated": {
        "category": "transaction",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_quarantine_mismatch": {
        "category": "reconciliation",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_cross_tenant_linkage": {
        "category": "tenant_isolation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "verifier_authority_conflict": {
        "category": "governance",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "appraisal_policy_revoked_but_active": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "trusted_result_with_revoked_endorsement": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "trusted_result_with_revoked_reference": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_selected_with_untrusted_lineage": {
        "category": "linkage",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "transaction_committed_with_revoked_attestation": {
        "category": "transaction",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "update_rollback_required": {
        "category": "health",
        "status": "active",
        "severity": "degraded",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": False,
        "aliases": [],
    },
    "update_signature_missing": {
        "category": "transaction",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "update_signature_invalid": {
        "category": "transaction",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "update_provenance_missing": {
        "category": "transaction",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "update_blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "lima_it_remediation_blocked": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "retention_policy_missing": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "export_delete_policy_missing": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "idp_mfa_missing": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "task_blocked": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "tenant_mismatch": {
        "category": "tenant_isolation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "customer_context_mismatch": {
        "category": "tenant_isolation",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "task_mismatch": {
        "category": "linkage",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "worker_mismatch": {
        "category": "linkage",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "action_type_mismatch": {
        "category": "linkage",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "tool_scope_mismatch": {
        "category": "linkage",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "resource_scope_widened": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "operation_scope_widened": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "guardian_decision_mismatch": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "approval_request_mismatch": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "approval_result_mismatch": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "approval_token_mismatch": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "token_verification_mismatch": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "nonce_replayed": {
        "category": "replay",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "token_expired": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "token_revoked": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "tainted_input": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "missing_evidence": {
        "category": "evidence",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": ["evidence_missing"],
    },
    "identity_provider_outage": {
        "category": "governance",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": False,
        "aliases": [],
    },
    "security_containment": {
        "category": "governance",
        "status": "active",
        "severity": "warning",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": False,
        "aliases": [],
    },
    "evidence_preservation": {
        "category": "governance",
        "status": "active",
        "severity": "warning",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": False,
        "aliases": [],
    },
    "worker_revoke": {
        "category": "governance",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": False,
        "aliases": [],
    },
    "mfa_required": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "device_untrusted": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "session_revoked": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "role_not_permitted": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "sod_required": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "breakglass_blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "attestation_required": {
        "category": "health",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "privileged_action_blocked": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "decision_scope_hash_mismatch": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "approval_binding_mismatch": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "decision_expired": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "decision_stale": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "decision_revoked": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "missing_expiry": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "ambiguous_timestamp": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "nonce_replay_denied": {
        "category": "replay",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "blocked_action_class_file_delete": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "delete_export_conflict_active": {
        "category": "export_delete",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "export_manifest_conflict_evidence_required": {
        "category": "export_delete",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "rollback_after_partial_commit": {
        "category": "transaction",
        "status": "active",
        "severity": "degraded",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "replay_store_unavailable": {
        "category": "replay",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "nonce_already_consumed": {
        "category": "replay",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "token_atomicity_ambiguous": {
        "category": "transaction",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "failed_closed_terminal_state": {
        "category": "transaction",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "evidence_writer_failure": {
        "category": "evidence",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "ledger_unavailable": {
        "category": "evidence",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "approved": {
        "category": "approval_binding",
        "status": "active",
        "severity": "info",
        "visibility": "operator_visible",
        "evidence_required": False,
        "fail_closed_required": False,
        "aliases": [],
    },
    "denied_by_approver": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "expired": {
        "category": "approval_binding",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "cancelled": {
        "category": "approval_binding",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "superseded": {
        "category": "approval_binding",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "partial_scope_requires_new_request": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "approval_missing": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "approval_denied": {
        "category": "approval_binding",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "sensitive_access_denied": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "evidence_unavailable": {
        "category": "evidence",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "evidence_writer_unavailable": {
        "category": "evidence",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "scope_mismatch": {
        "category": "linkage",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "identity_verification_failed": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "capability_mismatch": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "heartbeat_missed": {
        "category": "health",
        "status": "active",
        "severity": "degraded",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": False,
        "aliases": [],
    },
    "suspicious_tool_request": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "prompt_injection_suspected": {
        "category": "guardian",
        "status": "active",
        "severity": "critical",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "evidence_writer_failed": {
        "category": "evidence",
        "status": "active",
        "severity": "critical",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "operator_containment": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "update_verification_failed": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_unavailable": {
        "category": "health",
        "status": "active",
        "severity": "degraded",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_tainted_input_denied": {
        "category": "guardian",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_privileged_requires_approval": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_provider_blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_local_execution_blocked_mvp": {
        "category": "blocked_mvp",
        "status": "blocked",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_rbac_blocked": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "auditor_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_device_untrusted": {
        "category": "governance",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_route_fallback_denied": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "model_bundle_untrusted": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "policy_bundle_untrusted": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "runtime_bundle_untrusted": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "health_unknown": {
        "category": "health",
        "status": "active",
        "severity": "warning",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
    "health_degraded": {
        "category": "health",
        "status": "active",
        "severity": "degraded",
        "visibility": "operator_visible",
        "evidence_required": False,
        "fail_closed_required": False,
        "aliases": [],
    },
    "health_blocked": {
        "category": "health",
        "status": "active",
        "severity": "blocked",
        "visibility": "operator_visible",
        "evidence_required": True,
        "fail_closed_required": True,
        "aliases": [],
    },
}

CANONICAL_REASON_CODES = frozenset(REASON_CODE_REGISTRY)

ALIAS_TO_CANONICAL: dict[str, str] = {}
for _code, _meta in REASON_CODE_REGISTRY.items():
    for _alias in _meta.get("aliases", []):
        existing = ALIAS_TO_CANONICAL.get(_alias)
        if existing is not None and existing != _code:
            raise ValueError(f"duplicate alias mapping for {_alias}: {existing} vs {_code}")
        ALIAS_TO_CANONICAL[_alias] = _code

CONFLICT_DELETE_STATUSES = frozenset({"conflict_detected", "denied", "blocked_mvp"})
BLOCKING_HOLD_STATUSES = frozenset({"active", "conflict_with_delete", "blocked_mvp"})


def validate_taxonomy_version(version: str) -> str:
    """Validate taxonomy_version against supported in-repo versions."""

    if not isinstance(version, str) or not version:
        raise PolicyDenyError("taxonomy_version must be a non-empty string")
    if version not in SUPPORTED_TAXONOMY_VERSIONS:
        raise PolicyDenyError(f"unsupported taxonomy_version: {version}")
    return version


def get_reason_code_metadata(reason_code: str, *, allow_alias: bool = True) -> dict[str, Any]:
    """Resolve registry metadata for a reason code, optionally through alias mapping."""

    if reason_code in REASON_CODE_REGISTRY:
        metadata = dict(REASON_CODE_REGISTRY[reason_code])
        metadata["canonical_reason_code"] = reason_code
        metadata["is_alias"] = False
        return metadata
    if allow_alias and reason_code in ALIAS_TO_CANONICAL:
        canonical = ALIAS_TO_CANONICAL[reason_code]
        metadata = dict(REASON_CODE_REGISTRY[canonical])
        metadata["canonical_reason_code"] = canonical
        metadata["is_alias"] = True
        metadata["input_reason_code"] = reason_code
        return metadata
    raise PolicyDenyError(f"unknown reason code(s): {reason_code}")


def validate_registry_entry_metadata(reason_code: str) -> dict[str, Any]:
    """Validate category/status/severity for a registry entry."""

    metadata = get_reason_code_metadata(reason_code, allow_alias=False)
    category = metadata.get("category")
    status = metadata.get("status")
    severity = metadata.get("severity")
    if category not in REASON_CODE_CATEGORIES:
        raise PolicyDenyError(f"invalid reason category for {reason_code}: {category}")
    if status not in REASON_CODE_STATUSES:
        raise PolicyDenyError(f"invalid reason status for {reason_code}: {status}")
    if severity not in REASON_CODE_SEVERITIES:
        raise PolicyDenyError(f"invalid reason severity for {reason_code}: {severity}")
    return metadata


def normalize_reason_code(
    reason_code: str,
    *,
    allow_deprecated: bool = True,
    unknown_reason_code_policy: str = "fail_closed",
) -> str:
    """Return canonical reason code, honoring alias mapping and policy guards."""

    if unknown_reason_code_policy not in UNKNOWN_REASON_CODE_POLICIES:
        raise PolicyDenyError(f"unknown_reason_code_policy is invalid: {unknown_reason_code_policy}")

    try:
        metadata = get_reason_code_metadata(reason_code, allow_alias=True)
    except PolicyDenyError:
        if unknown_reason_code_policy in {"fail_closed", "blocked_mvp"}:
            raise
        return reason_code

    status = metadata.get("status")
    if status == "reserved":
        raise PolicyDenyError(f"reserved reason code cannot be used: {reason_code}")
    if status == "deprecated" and not allow_deprecated:
        raise PolicyDenyError(f"deprecated reason code not allowed: {reason_code}")
    if status == "deprecated" and isinstance(metadata.get("replaced_by"), str):
        return str(metadata["replaced_by"])
    return str(metadata["canonical_reason_code"])


def validate_reason_codes(
    reason_codes: list[str],
    *,
    allow_deprecated: bool = True,
    unknown_reason_code_policy: str = "fail_closed",
) -> list[str]:
    """Validate and normalize reason codes against the canonical in-repo registry."""

    if not isinstance(reason_codes, list):
        raise PolicyDenyError("reason_codes must be a list")
    normalized = {
        normalize_reason_code(
            code,
            allow_deprecated=allow_deprecated,
            unknown_reason_code_policy=unknown_reason_code_policy,
        )
        for code in reason_codes
    }
    return sorted(normalized)


def classify_reason_code_set(
    reason_codes: list[str],
    *,
    unknown_reason_code_policy: str = "fail_closed",
    deprecated_reason_code_policy: str = "allow_with_warning",
    compatibility_status: str = "compatible",
) -> dict[str, Any]:
    """Classify reason-code set for fail-closed metadata posture."""

    if unknown_reason_code_policy not in UNKNOWN_REASON_CODE_POLICIES:
        raise PolicyDenyError(f"unknown_reason_code_policy is invalid: {unknown_reason_code_policy}")
    if deprecated_reason_code_policy not in DEPRECATED_REASON_CODE_POLICIES:
        raise PolicyDenyError(
            f"deprecated_reason_code_policy is invalid: {deprecated_reason_code_policy}"
        )

    try:
        normalized = validate_reason_codes(
            reason_codes,
            allow_deprecated=True,
            unknown_reason_code_policy=unknown_reason_code_policy,
        )
    except PolicyDenyError:
        return {
            "raw_reason_codes": sorted(set(reason_codes)),
            "reason_codes": [],
            "deprecated_present": False,
            "fail_closed": True,
            "blocked": True,
            "can_authorize": False,
        }

    deprecated_present = False
    blocked_or_critical_present = False
    fail_closed_required = compatibility_status in {"breaking_change", "blocked_mvp"}
    for code in normalized:
        metadata = validate_registry_entry_metadata(code)
        if metadata["status"] == "deprecated":
            deprecated_present = True
        if metadata["status"] == "blocked" or metadata["severity"] in {"blocked", "critical"}:
            blocked_or_critical_present = True
        if metadata.get("fail_closed_required"):
            fail_closed_required = True

    if compatibility_status in {"breaking_change", "blocked_mvp"}:
        return {
            "raw_reason_codes": sorted(set(reason_codes)),
            "reason_codes": normalized,
            "deprecated_present": deprecated_present,
            "fail_closed": True,
            "blocked": True,
            "can_authorize": False,
        }

    if deprecated_present and deprecated_reason_code_policy in {"fail_closed", "blocked_mvp"}:
        return {
            "raw_reason_codes": sorted(set(reason_codes)),
            "reason_codes": normalized,
            "deprecated_present": True,
            "fail_closed": True,
            "blocked": True,
            "can_authorize": False,
        }

    return {
        "raw_reason_codes": sorted(set(reason_codes)),
        "reason_codes": normalized,
        "deprecated_present": deprecated_present,
        "fail_closed": fail_closed_required or blocked_or_critical_present,
        "blocked": blocked_or_critical_present,
        "can_authorize": False,
    }


def classify_export_delete_conflict(payload: dict[str, Any]) -> dict[str, Any]:
    """Classify export/delete conflict metadata in memory only."""

    reason_codes = payload.get("reason_codes") or []
    normalized_reasons = validate_reason_codes(reason_codes)
    reason_classification = classify_reason_code_set(
        normalized_reasons,
        unknown_reason_code_policy=str(payload.get("unknown_reason_code_policy") or "fail_closed"),
        deprecated_reason_code_policy=str(
            payload.get("deprecated_reason_code_policy") or "allow_with_warning"
        ),
        compatibility_status=str(payload.get("compatibility_status") or "compatible"),
    )

    preservation_hold_status = payload.get("preservation_hold_status")
    delete_review_status = payload.get("delete_review_status")
    export_review_status = payload.get("export_review_status")
    evidence_refs = payload.get("evidence_refs") or []
    conflict_evidence_refs = payload.get("conflict_evidence_refs") or []

    if preservation_hold_status in BLOCKING_HOLD_STATUSES and delete_review_status == "approved":
        raise PolicyDenyError("preservation hold conflict blocks delete approval")
    if delete_review_status in CONFLICT_DELETE_STATUSES and not conflict_evidence_refs:
        raise PolicyDenyError("conflict-detected delete review requires conflict evidence refs")
    if export_review_status in {"denied", "failed_closed", "blocked_mvp"} and not evidence_refs:
        raise PolicyDenyError("denied/failed/blocked export review requires evidence refs")

    return {
        "raw_reason_codes": sorted(set(reason_codes)),
        "reason_codes": normalized_reasons,
        "delete_blocked_by_hold": preservation_hold_status in BLOCKING_HOLD_STATUSES,
        "conflict_detected": delete_review_status in CONFLICT_DELETE_STATUSES,
        "export_denied_or_blocked": export_review_status in {"denied", "failed_closed", "blocked_mvp"},
        "reason_fail_closed": bool(reason_classification["fail_closed"]),
        "deprecated_reason_present": bool(reason_classification["deprecated_present"]),
        "can_authorize": False,
    }
